name: After deploy beta index

on: 
  workflow_dispatch:

jobs:
  wait-for-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: timeless-beta
          service_account_key: ${{ secrets.TIMELESS_BETA_FIREBASE_SA }}
          export_default_credentials: true

      - name: List opreations
        run: gcloud firestore operations list
